platform :ios,’9.0’
# dismiss all third party warning
inhibit_all_warnings!

target 'HttpRequestDemo' do

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

    pod 'AFNetworking', '~> 3.1.0'

end
